#!/usr/bin/env bash
#
# build.sh - Build script for beranode CLI
#
# This script combines all modular source files from src/ into a single
# beranode executable file for distribution.
#
# Usage: ./build.sh [output_file]
#   output_file: Optional output path (default: ./beranode)
#

set -e

# Determine script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="${SCRIPT_DIR}/src"
OUTPUT_FILE="${1:-${SCRIPT_DIR}/beranode}"

# Color output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[0;33m'
RESET='\033[0m'

echo -e "${BLUE}Building beranode CLI...${RESET}"

# Check if src directory exists
if [[ ! -d "$SRC_DIR" ]]; then
    echo -e "${YELLOW}Error: src directory not found at $SRC_DIR${RESET}"
    exit 1
fi

# Create a temporary file for building
TEMP_FILE=$(mktemp)

# Function to strip shebang and header comments from module files
strip_module_header() {
    local file="$1"
    # Skip lines starting with #!/usr/bin/env bash and initial comment block
    awk '
        BEGIN { in_header = 1; first_line = 1 }
        /^#!/ && first_line { first_line = 0; next }
        /^#/ && in_header { next }
        /^$/ && in_header { next }
        { in_header = 0; print }
    ' "$file"
}

# Function to add a section separator
add_section() {
    local section_name="$1"
    local file_path="$2"

    cat >> "$TEMP_FILE" <<EOF

# =============================================================================
# ${section_name}
# Source: ${file_path}
# =============================================================================

EOF
}

# Start building the output file
cat > "$TEMP_FILE" <<'EOF'
#!/usr/bin/env bash
#
# beranode - CLI for managing Berachain nodes
#
# This file is auto-generated by build.sh from modular sources in src/
# Do not edit this file directly. Instead, edit the source files and rebuild.
#
# Usage: beranode <command> [options]
#

set -e

EOF

# Add each module in dependency order
modules=(
    "lib/constants.sh"
    "lib/logging.sh"
    "lib/utils.sh"
    "lib/genesis.sh"
    "lib/node.sh"
    "commands/common.sh"
    "commands/init.sh"
    "commands/start.sh"
    "core/dispatcher.sh"
)

for module in "${modules[@]}"; do
    module_path="${SRC_DIR}/${module}"

    if [[ -f "$module_path" ]]; then
        echo -e "${BLUE}  Adding: ${module}${RESET}"
        add_section "$(basename "$module" .sh)" "$module" >> "$TEMP_FILE"
        strip_module_header "$module_path" >> "$TEMP_FILE"
        echo "" >> "$TEMP_FILE"
    else
        echo -e "${YELLOW}  Warning: Module not found: ${module}${RESET}"
    fi
done

# Add the main entry point
cat >> "$TEMP_FILE" <<'EOF'

# =============================================================================
# Entry Point - Main script execution
# =============================================================================

main "$@"
EOF

# Move temp file to output and make executable
mv "$TEMP_FILE" "$OUTPUT_FILE"
chmod +x "$OUTPUT_FILE"

echo -e "${GREEN}✓ Build complete: ${OUTPUT_FILE}${RESET}"
echo -e "${BLUE}  Lines: $(wc -l < "$OUTPUT_FILE")${RESET}"
echo -e "${BLUE}  Size: $(du -h "$OUTPUT_FILE" | cut -f1)${RESET}"
